### ISSUE TITLE
what is the coco_list.txt?

### ISSUE THREAD

**Issue by chunniunai220ml** [pascal1129/yolo_person_detect#4]
when I use the coco_to_yolo.py, I did not konw about coco_list.txt that is not in the downloaded dataset . so How get the txt?

**Comment by chunniunai220ml** [comment]
if I just extract person, could i change the code classes=get_classes_and_index('path/to/coco_list.txt')
to classes={0:'person'} ?

**Comment by wyxplus** [comment]
excuse me,how did you do for using coco_list.txt?  I have the same question.

**Comment by wyxplus** [comment]
> if I just extract person, could i change the code classes=get_classes_and_index('path/to/coco_list.txt')
> to classes={0:'person'} ?

Excuse me,how did you do for using the coco_list.txt? I have the same question.

**Comment by wyxplus** [comment]
> > if I just extract person, could i change the code classes=get_classes_and_index('path/to/coco_list.txt')
> > to classes={0:'person'} ?
> 
> Excuse me,how did you do for using the coco_list.txt? I have the same question.

OK,i find it.
https://blog.csdn.net/Jinlong_Xu/article/details/75577007
